from __future__ import annotations

import re
from pathlib import Path

from goals.models import (
    ArchitectureBrief,
    ArchitectureBriefItem,
    ArchitectureCheckFinding,
    ArchitectureCheckReport,
    ArchitectureEdge,
    ArchitectureNode,
    GoalArchitectureMap,
    GoalSnapshot,
    PhaseStatus,
    utc_now,
)
from goals.storage import atomic_write_text

CODE_EXTENSIONS = {
    ".go",
    ".java",
    ".js",
    ".jsx",
    ".kt",
    ".mjs",
    ".py",
    ".rb",
    ".rs",
    ".swift",
    ".ts",
    ".tsx",
}
PATH_EVIDENCE_EXTENSIONS = CODE_EXTENSIONS | {
    ".cfg",
    ".css",
    ".html",
    ".json",
    ".md",
    ".toml",
    ".yaml",
    ".yml",
}
SKIP_DIRS = {
    ".agent-workflow",
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "__pycache__",
    "build",
    "dist",
    "htmlcov",
    "node_modules",
}


def architecture_for_snapshot(snapshot: GoalSnapshot) -> GoalArchitectureMap:
    if snapshot.architecture is not None:
        return snapshot.architecture
    nodes = [_node_for_phase(phase) for phase in snapshot.phases]
    edges = [
        ArchitectureEdge(
            from_node=left.phase_id,
            to_node=right.phase_id,
            relation="next_phase",
            plain_summary=f"{left.title} informs {right.title}.",
        )
        for left, right in zip(snapshot.phases, snapshot.phases[1:])
    ]
    return GoalArchitectureMap(
        title=f"Architecture map for {snapshot.objective}",
        overview=(
            "This map is generated from the goal phases until an agent records a "
            "project-specific architecture map."
        ),
        nodes=nodes,
        edges=edges,
        questions=[
            "Does each phase still match the goal?",
            "Is any important system change missing from this map?",
            "Is anything marked built without evidence?",
        ],
        updated_at=utc_now(),
    )


def render_architecture_markdown(architecture: GoalArchitectureMap, output_path: Path) -> None:
    diagram = render_mermaid(architecture)
    brief = build_architecture_brief(architecture)
    brief_markdown = render_architecture_brief(brief).replace(
        "# Architecture Brief", "## Architecture Brief", 1
    )
    nodes = "\n".join(_node_markdown(node) for node in architecture.nodes)
    questions = _bullets(architecture.questions or ["No open architecture questions recorded."])
    markdown = f"""# {architecture.title}

{architecture.overview}

{brief_markdown}

## Diagram

```mermaid
{diagram}
```

## Build Status

{nodes}

## Questions to Check

{questions}

_Generated by Goals from goal state. This file is read-only output unless an agent records a new architecture map._
"""
    atomic_write_text(output_path, markdown)


def render_mermaid(architecture: GoalArchitectureMap) -> str:
    lines = ["flowchart LR"]
    if not architecture.nodes:
        lines.append('  empty["No architecture nodes recorded"]')
        return "\n".join(lines)
    for node in architecture.nodes:
        lines.append(f'  {_mermaid_id(node.node_id)}["{_mermaid_label(node)}"]')
    for edge in architecture.edges:
        relation = edge.plain_summary or edge.relation
        lines.append(
            f"  {_mermaid_id(edge.from_node)} -->|{_mermaid_text(relation)}| "
            f"{_mermaid_id(edge.to_node)}"
        )
    return "\n".join(lines)


def build_architecture_brief(architecture: GoalArchitectureMap) -> ArchitectureBrief:
    counts = architecture_status_counts(architecture)
    evidence_gaps = [
        _brief_item(node) for node in architecture.nodes if _needs_architecture_evidence(node)
    ]
    review_focus = _review_focus(architecture, evidence_gaps)
    total_nodes = len(architecture.nodes)
    built = counts.get("built", 0)
    blocked = counts.get("blocked", 0)
    summary = (
        f"{built}/{total_nodes} architecture node(s) are built"
        if total_nodes
        else "No architecture nodes are recorded yet"
    )
    if blocked:
        summary += f"; {blocked} blocked."
    elif evidence_gaps:
        summary += f"; {len(evidence_gaps)} node(s) need evidence or review."
    else:
        summary += "; no evidence gaps detected."
    return ArchitectureBrief(
        title=architecture.title,
        summary=summary,
        status_counts=counts,
        review_focus=review_focus,
        evidence_gaps=evidence_gaps,
        open_questions=list(architecture.questions),
    )


def analyze_code_architecture(
    snapshot: GoalSnapshot,
    worktree: Path | None = None,
) -> ArchitectureCheckReport:
    """Compare architecture map claims with code files and recorded file evidence."""

    worktree = worktree or Path(snapshot.topology.worktree_path)
    architecture = architecture_for_snapshot(snapshot)
    explicit_map = snapshot.architecture is not None
    architecture_text = _architecture_search_text(architecture)
    changed_files = _changed_files(snapshot)
    source_paths = _source_code_paths(worktree) if explicit_map else []
    findings: list[ArchitectureCheckFinding] = []

    for path_text in changed_files:
        path = worktree / path_text
        if (
            _is_code_path(path_text)
            and path.exists()
            and path_text.lower() not in architecture_text
        ):
            findings.append(
                ArchitectureCheckFinding(
                    severity="p1",
                    area="coverage",
                    summary=f"Changed code file is missing from the architecture map: {path_text}",
                    detail="The goal recorded this changed file as evidence, but no architecture node references it.",
                    suggested_action="Update the architecture map or node evidence before accepting the phase.",
                    evidence_refs=[path_text],
                )
            )

    for ref in _architecture_evidence_refs(architecture):
        if not _looks_like_path_ref(ref):
            continue
        path = worktree / ref
        if not path.exists():
            findings.append(
                ArchitectureCheckFinding(
                    severity="p1",
                    area="evidence",
                    summary=f"Architecture evidence path does not exist: {ref}",
                    detail="A map node points at a file path that is not present in the worktree.",
                    suggested_action="Fix the evidence reference, add the missing file, or replace it with a check/source reference.",
                    evidence_refs=[ref],
                )
            )

    for code_path in source_paths:
        if _is_represented(code_path, architecture_text):
            continue
        findings.append(
            ArchitectureCheckFinding(
                severity="p2",
                area="coverage",
                summary=f"Code surface is not represented in the architecture map: {code_path}",
                detail="The map may still be correct, but this source file is not named by any node summary, note, or evidence reference.",
                suggested_action="Decide whether this code belongs in an existing architecture node or should be intentionally ignored.",
                evidence_refs=[code_path],
            )
        )

    blocking = [finding for finding in findings if finding.severity in {"p0", "p1"}]
    return ArchitectureCheckReport(
        goal_id=snapshot.goal_id,
        passed=not blocking,
        summary=(
            f"Checked {len(changed_files)} recorded changed file(s)"
            + (f" and {len(source_paths)} source code surface(s)" if explicit_map else "")
            + f": {len([finding for finding in findings if finding.severity == 'p1'])} important, "
            f"{len([finding for finding in findings if finding.severity == 'p2'])} advisory."
        ),
        findings=findings,
        user_questions=[finding.summary for finding in findings if finding.needs_user],
        agent_actions=_unique(
            [
                finding.suggested_action
                for finding in findings
                if finding.suggested_action and not finding.needs_user
            ]
        ),
    )


def render_architecture_check_report(report: ArchitectureCheckReport) -> str:
    lines = [
        "# Code-Derived Architecture Check",
        "",
        f"Goal: {report.goal_id}",
        f"Overall: {'pass' if report.passed else 'needs attention'}",
        "",
        report.summary,
        "",
        "## Needs The User",
        _bullets(
            report.user_questions or ["No architecture/code decision is waiting on the user."]
        ),
        "",
        "## Agent Can Work On",
        _bullets(report.agent_actions or ["No architecture/code cleanup is currently suggested."]),
        "",
        "## Findings",
    ]
    if not report.findings:
        lines.append("- No code-derived architecture issues found.")
    for finding in report.findings:
        marker = " user" if finding.needs_user else ""
        lines.append(f"- [{finding.severity.upper()}][{finding.area}{marker}] {finding.summary}")
        if finding.detail:
            lines.append(f"  Detail: {finding.detail}")
        if finding.evidence_refs:
            lines.append(f"  Evidence: {', '.join(finding.evidence_refs)}")
        if finding.suggested_action:
            lines.append(f"  Next: {finding.suggested_action}")
    return "\n".join(lines) + "\n"


def render_architecture_brief(brief: ArchitectureBrief) -> str:
    lines = [
        "# Architecture Brief",
        "",
        brief.summary,
        "",
        "### Status Counts",
        _bullets(_count_lines(brief.status_counts) or ["No nodes recorded."]),
        "",
        "### Review Focus",
        _bullets(brief.review_focus or ["No architecture review focus recorded."]),
        "",
        "### Evidence Gaps",
    ]
    if not brief.evidence_gaps:
        lines.append("  - No architecture evidence gaps detected.")
    for item in brief.evidence_gaps:
        lines.append(f"  - {item.label}: {item.review_focus}")
    lines.extend(
        [
            "",
            "### Open Questions",
            _bullets(brief.open_questions or ["No open architecture questions recorded."]),
        ]
    )
    return "\n".join(lines)


def architecture_status_counts(architecture: GoalArchitectureMap) -> dict[str, int]:
    counts: dict[str, int] = {}
    for node in architecture.nodes:
        counts[node.status] = counts.get(node.status, 0) + 1
    return counts


def _node_for_phase(phase) -> ArchitectureNode:
    evidence_refs: list[str] = []
    technical_notes = list(phase.acceptance_criteria)
    if phase.evidence is not None:
        evidence_refs.extend(phase.evidence.changed_files)
        evidence_refs.extend(phase.evidence.checks_run)
        if phase.evidence.known_gaps:
            technical_notes.extend(phase.evidence.known_gaps)
    return ArchitectureNode(
        node_id=phase.phase_id,
        label=phase.title,
        plain_summary=phase.goal,
        status=_status_for_phase(phase.status),
        owner_phase=phase.phase_id,
        user_value=phase.goal,
        evidence_refs=evidence_refs,
        technical_notes=technical_notes,
    )


def _brief_item(node: ArchitectureNode) -> ArchitectureBriefItem:
    return ArchitectureBriefItem(
        node_id=node.node_id,
        label=node.label,
        status=node.status,
        plain_summary=node.plain_summary,
        owner_phase=node.owner_phase,
        user_value=node.user_value,
        evidence_refs=list(node.evidence_refs),
        review_focus=_node_review_focus(node),
    )


def _needs_architecture_evidence(node: ArchitectureNode) -> bool:
    if node.status in {"built", "in_progress", "blocked"} and not node.evidence_refs:
        return True
    if node.status == "blocked":
        return True
    return False


def _node_review_focus(node: ArchitectureNode) -> str:
    if node.status == "blocked":
        return "Resolve the blocker or decide whether this node should be deferred."
    if node.status == "built" and not node.evidence_refs:
        return "Built node has no evidence references; verify proof before trusting it."
    if node.status == "in_progress" and not node.evidence_refs:
        return "In-progress node needs evidence before review or acceptance."
    return "Check whether this node still matches the goal and recorded evidence."


def _review_focus(
    architecture: GoalArchitectureMap,
    evidence_gaps: list[ArchitectureBriefItem],
) -> list[str]:
    focus: list[str] = []
    blocked = [node for node in architecture.nodes if node.status == "blocked"]
    in_progress = [node for node in architecture.nodes if node.status == "in_progress"]
    if blocked:
        focus.append(
            f"Resolve or explicitly defer blocked architecture node(s): "
            f"{', '.join(node.label for node in blocked[:4])}."
        )
    if evidence_gaps:
        focus.append(
            f"Verify evidence for {len(evidence_gaps)} architecture node(s) before treating the map as trustworthy."
        )
    if in_progress:
        focus.append(
            f"Review in-progress node(s): {', '.join(node.label for node in in_progress[:4])}."
        )
    if architecture.questions:
        focus.append("Answer or explicitly defer the open architecture questions.")
    if not focus:
        focus.append(
            "Architecture map has no detected review gaps; compare it with changed files before closing."
        )
    return focus


def _count_lines(counts: dict[str, int]) -> list[str]:
    return [f"{status}: {count}" for status, count in sorted(counts.items())]


def _changed_files(snapshot: GoalSnapshot) -> list[str]:
    paths: list[str] = []
    for phase in snapshot.phases:
        if phase.evidence is None:
            continue
        paths.extend(phase.evidence.changed_files)
    return _unique(paths)


def _architecture_evidence_refs(architecture: GoalArchitectureMap) -> list[str]:
    refs: list[str] = []
    for node in architecture.nodes:
        refs.extend(node.evidence_refs)
    return _unique(refs)


def _architecture_search_text(architecture: GoalArchitectureMap) -> str:
    parts = [architecture.title, architecture.overview]
    for node in architecture.nodes:
        parts.extend(
            [
                node.node_id,
                node.label,
                node.plain_summary,
                node.owner_phase or "",
                node.user_value,
                *node.evidence_refs,
                *node.technical_notes,
            ]
        )
    return "\n".join(parts).lower()


def _source_code_paths(worktree: Path) -> list[str]:
    if not worktree.exists():
        return []
    roots = [
        path for path in [worktree / "src", worktree / "app", worktree / "apps"] if path.exists()
    ]
    if not roots:
        roots = [worktree]
    paths: list[str] = []
    for root in roots:
        for path in root.rglob("*"):
            if not path.is_file() or _is_skipped(path, worktree):
                continue
            if path.suffix.lower() in CODE_EXTENSIONS:
                paths.append(path.relative_to(worktree).as_posix())
    return sorted(_unique(paths))


def _is_skipped(path: Path, worktree: Path) -> bool:
    try:
        relative = path.relative_to(worktree)
    except ValueError:
        return True
    return any(part in SKIP_DIRS for part in relative.parts)


def _looks_like_path_ref(value: str) -> bool:
    if " " in value or value.startswith(("http://", "https://")):
        return False
    path = Path(value)
    return "/" in value or value.startswith(".") or path.suffix.lower() in PATH_EVIDENCE_EXTENSIONS


def _is_code_path(value: str) -> bool:
    return Path(value).suffix.lower() in CODE_EXTENSIONS


def _is_represented(path: str, architecture_text: str) -> bool:
    lower = path.lower()
    stem = Path(path).stem.lower()
    return lower in architecture_text or stem in architecture_text


def _status_for_phase(status: PhaseStatus) -> str:
    return {
        PhaseStatus.PENDING: "planned",
        PhaseStatus.IN_PROGRESS: "in_progress",
        PhaseStatus.NEEDS_REVIEW: "in_progress",
        PhaseStatus.ACCEPTED: "built",
        PhaseStatus.BLOCKED: "blocked",
    }[status]


def _node_markdown(node: ArchitectureNode) -> str:
    evidence = _bullets(node.evidence_refs or ["No evidence recorded yet."])
    notes = _bullets(node.technical_notes or ["No technical notes recorded."])
    return f"""### {node.label}

- Status: `{node.status}`
- Plain summary: {node.plain_summary}
- User value: {node.user_value or "Not recorded."}
- Phase: `{node.owner_phase or "unassigned"}`
- Evidence:
{evidence}
- Technical notes:
{notes}
"""


def _bullets(items: list[str]) -> str:
    return "\n".join(f"  - {item}" for item in items)


def _unique(items: list[str]) -> list[str]:
    seen: set[str] = set()
    unique: list[str] = []
    for item in items:
        if item in seen:
            continue
        seen.add(item)
        unique.append(item)
    return unique


def _mermaid_id(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]", "_", value).strip("_")
    return f"n_{cleaned or 'node'}"


def _mermaid_label(node: ArchitectureNode) -> str:
    return _mermaid_text(f"{node.label}\\n{node.status}")


def _mermaid_text(value: str) -> str:
    return value.replace('"', "'").replace("|", "/").replace("\n", "<br/>")
