from __future__ import annotations

import re
from pathlib import Path

from goals.models import (
    ArchitectureEdge,
    ArchitectureNode,
    GoalArchitectureMap,
    GoalSnapshot,
    PhaseStatus,
    utc_now,
)
from goals.storage import atomic_write_text


def architecture_for_snapshot(snapshot: GoalSnapshot) -> GoalArchitectureMap:
    if snapshot.architecture is not None:
        return snapshot.architecture
    nodes = [_node_for_phase(phase) for phase in snapshot.phases]
    edges = [
        ArchitectureEdge(
            from_node=left.phase_id,
            to_node=right.phase_id,
            relation="next_phase",
            plain_summary=f"{left.title} informs {right.title}.",
        )
        for left, right in zip(snapshot.phases, snapshot.phases[1:])
    ]
    return GoalArchitectureMap(
        title=f"Architecture map for {snapshot.objective}",
        overview=(
            "This map is generated from the goal phases until an agent records a "
            "project-specific architecture map."
        ),
        nodes=nodes,
        edges=edges,
        questions=[
            "Does each phase still match the goal?",
            "Is any important system change missing from this map?",
            "Is anything marked built without evidence?",
        ],
        updated_at=utc_now(),
    )


def render_architecture_markdown(architecture: GoalArchitectureMap, output_path: Path) -> None:
    diagram = render_mermaid(architecture)
    nodes = "\n".join(_node_markdown(node) for node in architecture.nodes)
    questions = _bullets(architecture.questions or ["No open architecture questions recorded."])
    markdown = f"""# {architecture.title}

{architecture.overview}

## Diagram

```mermaid
{diagram}
```

## Build Status

{nodes}

## Questions to Check

{questions}

_Generated by Goals from goal state. This file is read-only output unless an agent records a new architecture map._
"""
    atomic_write_text(output_path, markdown)


def render_mermaid(architecture: GoalArchitectureMap) -> str:
    lines = ["flowchart LR"]
    if not architecture.nodes:
        lines.append('  empty["No architecture nodes recorded"]')
        return "\n".join(lines)
    for node in architecture.nodes:
        lines.append(f'  {_mermaid_id(node.node_id)}["{_mermaid_label(node)}"]')
    for edge in architecture.edges:
        relation = edge.plain_summary or edge.relation
        lines.append(
            f"  {_mermaid_id(edge.from_node)} -->|{_mermaid_text(relation)}| "
            f"{_mermaid_id(edge.to_node)}"
        )
    return "\n".join(lines)


def architecture_status_counts(architecture: GoalArchitectureMap) -> dict[str, int]:
    counts: dict[str, int] = {}
    for node in architecture.nodes:
        counts[node.status] = counts.get(node.status, 0) + 1
    return counts


def _node_for_phase(phase) -> ArchitectureNode:
    evidence_refs: list[str] = []
    technical_notes = list(phase.acceptance_criteria)
    if phase.evidence is not None:
        evidence_refs.extend(phase.evidence.changed_files)
        evidence_refs.extend(phase.evidence.checks_run)
        if phase.evidence.known_gaps:
            technical_notes.extend(phase.evidence.known_gaps)
    return ArchitectureNode(
        node_id=phase.phase_id,
        label=phase.title,
        plain_summary=phase.goal,
        status=_status_for_phase(phase.status),
        owner_phase=phase.phase_id,
        user_value=phase.goal,
        evidence_refs=evidence_refs,
        technical_notes=technical_notes,
    )


def _status_for_phase(status: PhaseStatus) -> str:
    return {
        PhaseStatus.PENDING: "planned",
        PhaseStatus.IN_PROGRESS: "in_progress",
        PhaseStatus.NEEDS_REVIEW: "in_progress",
        PhaseStatus.ACCEPTED: "built",
        PhaseStatus.BLOCKED: "blocked",
    }[status]


def _node_markdown(node: ArchitectureNode) -> str:
    evidence = _bullets(node.evidence_refs or ["No evidence recorded yet."])
    notes = _bullets(node.technical_notes or ["No technical notes recorded."])
    return f"""### {node.label}

- Status: `{node.status}`
- Plain summary: {node.plain_summary}
- User value: {node.user_value or "Not recorded."}
- Phase: `{node.owner_phase or "unassigned"}`
- Evidence:
{evidence}
- Technical notes:
{notes}
"""


def _bullets(items: list[str]) -> str:
    return "\n".join(f"  - {item}" for item in items)


def _mermaid_id(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]", "_", value).strip("_")
    return f"n_{cleaned or 'node'}"


def _mermaid_label(node: ArchitectureNode) -> str:
    return _mermaid_text(f"{node.label}\\n{node.status}")


def _mermaid_text(value: str) -> str:
    return value.replace('"', "'").replace("|", "/").replace("\n", "<br/>")
