from __future__ import annotations

from html import escape
from pathlib import Path

from goals.git_ops import source_commit
from goals.models import GoalSnapshot
from goals.storage import atomic_write_text


def render_dashboard(snapshot: GoalSnapshot, output_path: Path) -> None:
    status = escape(snapshot.status)
    current = escape(snapshot.current_phase or "none")
    phase_rows = "\n".join(
        f"<tr><td>{escape(p.phase_id)}</td><td>{escape(p.title)}</td>"
        f"<td>{escape(p.status)}</td><td>{escape(p.goal)}</td></tr>"
        for p in snapshot.phases
    )
    decisions = (
        "\n".join(
            f"<li><strong>{escape(d.title)}</strong>: {escape(d.plain_summary)} "
            f"<br><em>Recommended:</em> {escape(d.recommendation)}"
            f"<br><code>{escape(d.suggested_reply or 'Reply with your preferred option.')}</code></li>"
            for d in snapshot.decisions
        )
        or "<li>No decisions waiting on you.</li>"
    )
    evidence = "\n".join(
        f"<li>{escape(p.phase_id)}: {escape((p.evidence.notes if p.evidence else 'No evidence yet'))}</li>"
        for p in snapshot.phases
    )
    html = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Goals Dashboard - {escape(snapshot.goal_id)}</title>
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; margin: 2rem; line-height: 1.45; color: #1f2937; }}
    header, section {{ max-width: 1000px; margin: 0 auto 1.5rem; }}
    .status {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: .75rem; }}
    .tile {{ border: 1px solid #d1d5db; border-radius: 8px; padding: .9rem; background: #f9fafb; }}
    table {{ width: 100%; border-collapse: collapse; }}
    th, td {{ border-bottom: 1px solid #e5e7eb; text-align: left; padding: .6rem; vertical-align: top; }}
    code {{ background: #eef2ff; padding: .1rem .25rem; border-radius: 4px; }}
  </style>
</head>
<body>
  <header>
    <h1>{escape(snapshot.objective)}</h1>
    <p>{escape(snapshot.why)}</p>
    <div class="status">
      <div class="tile"><strong>Status</strong><br>{status}</div>
      <div class="tile"><strong>Current step</strong><br>{current}</div>
      <div class="tile"><strong>Waiting on</strong><br>{"you" if snapshot.status == "blocked" else "agent"}</div>
      <div class="tile"><strong>Last updated</strong><br>{escape(snapshot.last_updated)}</div>
    </div>
  </header>
  <section>
    <h2>Plan</h2>
    <table><thead><tr><th>ID</th><th>Step</th><th>Status</th><th>Plain goal</th></tr></thead><tbody>{phase_rows}</tbody></table>
  </section>
  <section>
    <h2>Decisions Needed</h2>
    <ul>{decisions}</ul>
  </section>
  <section>
    <h2>Proof and Evidence</h2>
    <ul>{evidence}</ul>
  </section>
  <section>
    <h2>Technical Details</h2>
    <p>Goal ID: <code>{escape(snapshot.goal_id)}</code></p>
    <p>Event offset: <code>{snapshot.event_count}</code></p>
    <p>Source commit: <code>{escape(source_commit(Path(snapshot.topology.worktree_path)))}</code></p>
    <p>Generated by Goals from sanitized snapshot state. This page is read-only.</p>
  </section>
</body>
</html>
"""
    atomic_write_text(output_path, html)
