"""Portable, vendor-neutral goal artifacts.

This is the part of Goals that stays valuable even as Claude Code and Codex
evolve their own native loops. It turns the internal goal snapshot into:

1. A committable portable spec (`.goals/goal-state.json` + `.goals/GOAL.md`)
   that any agent can read to resume the task. The "AGENTS.md for task state".
2. A managed context block synced into `AGENTS.md` and `CLAUDE.md`, so a team
   using both Claude Code and Codex never drifts.
3. A native stop-condition emitted from the current phase's acceptance criteria,
   ready to paste into Claude Code's `/goal` or Codex's task definition.

Unlike `.agent-workflow/` (local run state, git-ignored, may contain machine
paths), everything here is sanitized of local paths and meant to be committed.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Literal

from goals.models import (
    PORTABLE_SPEC_VERSION,
    ContextSyncResult,
    GoalSnapshot,
    NativeGoalEmission,
    Phase,
    PortableExport,
)
from goals.runtime import load_active_snapshot
from goals.storage import atomic_write_text

NativeAdapter = Literal["claude", "codex"]

CONTEXT_START = "<!-- goals:context:start -->"
CONTEXT_END = "<!-- goals:context:end -->"

#: Files the context block is synced into, in priority order. AGENTS.md is the
#: cross-vendor standard (read by Codex, Cursor, Aider, Gemini, ...); CLAUDE.md
#: is Claude Code's native memory file.
CONTEXT_TARGETS: tuple[str, ...] = ("AGENTS.md", "CLAUDE.md")


# --------------------------------------------------------------------------- #
# 1. Portable goal-state spec
# --------------------------------------------------------------------------- #
def build_portable_state(snapshot: GoalSnapshot) -> dict:
    """Build the vendor-neutral, path-free goal-state dict."""
    return {
        "spec_version": PORTABLE_SPEC_VERSION,
        "goal_id": snapshot.goal_id,
        "objective": snapshot.objective,
        "why": snapshot.why,
        "status": str(snapshot.status),
        "autonomy": snapshot.autonomy,
        "branch": snapshot.topology.branch,
        "current_phase": snapshot.current_phase,
        "definition_of_done": list(snapshot.definition_of_done),
        "phases": [_portable_phase(phase) for phase in snapshot.phases],
        "open_decisions": [
            {
                "id": decision.decision_id,
                "title": decision.title,
                "priority": decision.priority,
                "recommendation": decision.recommendation,
                "options": [option.label for option in decision.options],
            }
            for decision in snapshot.decisions
            if decision.priority == "blocking"
        ],
        "blockers": list(snapshot.blockers),
        "risks": list(snapshot.risks),
        "learnings": list(snapshot.learnings),
        "last_updated": snapshot.last_updated,
    }


def _portable_phase(phase: Phase) -> dict:
    evidence = None
    if phase.evidence is not None:
        evidence = {
            "acceptance_met": list(phase.evidence.acceptance_met),
            "acceptance_not_met": list(phase.evidence.acceptance_not_met),
            "checks_run": list(phase.evidence.checks_run),
            "known_gaps": list(phase.evidence.known_gaps),
            "confidence": phase.evidence.confidence,
        }
    return {
        "phase_id": phase.phase_id,
        "title": phase.title,
        "goal": phase.goal,
        "status": str(phase.status),
        "acceptance_criteria": list(phase.acceptance_criteria),
        "evidence": evidence,
    }


def render_goal_markdown(snapshot: GoalSnapshot) -> str:
    """Render the human- and agent-readable GOAL.md."""
    lines = [
        f"# Goal: {snapshot.objective}",
        "",
        "> Portable goal state generated by Goals "
        f"(spec v{PORTABLE_SPEC_VERSION}). Safe to commit. Any agent — Claude",
        "> Code, Codex, Cursor, Aider — can read this file (and "
        "`.goals/goal-state.json`)",
        "> to resume the task without losing the thread.",
        "",
        f"- **Status:** {snapshot.status}",
        f"- **Current phase:** {snapshot.current_phase or 'none'}",
        f"- **Branch:** `{snapshot.topology.branch}`",
    ]
    if snapshot.why:
        lines.append(f"- **Why:** {snapshot.why}")
    lines += ["", "## Definition of Done", *_bullets(snapshot.definition_of_done), ""]

    lines.append("## Phases")
    for phase in snapshot.phases:
        marker = "→ " if phase.phase_id == snapshot.current_phase else ""
        lines += ["", f"### {marker}{phase.phase_id} — {phase.title}  [{phase.status}]"]
        if phase.goal:
            lines.append(f"Goal: {phase.goal}")
        if phase.acceptance_criteria:
            lines.append("")
            met = set(phase.evidence.acceptance_met) if phase.evidence else set()
            for criterion in phase.acceptance_criteria:
                box = "x" if criterion in met else " "
                lines.append(f"- [{box}] {criterion}")
        if phase.evidence is not None:
            lines.append(
                f"- _Evidence: {len(phase.evidence.checks_run)} check(s) run, "
                f"confidence {phase.evidence.confidence:.1f}._"
            )

    blocking = [d for d in snapshot.decisions if d.priority == "blocking"]
    if blocking:
        lines += ["", "## Open Decisions (need the user)"]
        for decision in blocking:
            options = ", ".join(option.label for option in decision.options)
            lines.append(f"- **{decision.title}** — recommend: {decision.recommendation}")
            if options:
                lines.append(f"  - Options: {options}")

    for title, items in (
        ("Blockers", snapshot.blockers),
        ("Risks", snapshot.risks),
        ("Learnings", snapshot.learnings),
    ):
        if items:
            lines += ["", f"## {title}", *_bullets(items)]

    lines += [
        "",
        "## Machine-readable",
        f"See `.goals/goal-state.json` (portable spec v{PORTABLE_SPEC_VERSION}).",
        "",
    ]
    return "\n".join(lines)


def export_goal(cwd: Path) -> PortableExport:
    """Write the portable spec pair into `<worktree>/.goals/`."""
    snapshot = load_active_snapshot(cwd)
    worktree = Path(snapshot.topology.worktree_path)
    goals_dir = worktree / ".goals"
    state_path = goals_dir / "goal-state.json"
    markdown_path = goals_dir / "GOAL.md"
    payload = json.dumps(build_portable_state(snapshot), indent=2, ensure_ascii=False)
    atomic_write_text(state_path, payload + "\n")
    atomic_write_text(markdown_path, render_goal_markdown(snapshot))
    return PortableExport(
        spec_version=PORTABLE_SPEC_VERSION,
        goal_id=snapshot.goal_id,
        state_path=str(state_path),
        markdown_path=str(markdown_path),
        phase_count=len(snapshot.phases),
    )


# --------------------------------------------------------------------------- #
# 2. Context file converter / sync (AGENTS.md <-> CLAUDE.md)
# --------------------------------------------------------------------------- #
def render_context_block(snapshot: GoalSnapshot) -> str:
    """Render the managed block injected into AGENTS.md / CLAUDE.md."""
    current = _current_phase_or_none(snapshot)
    phase_line = (
        f"{current.phase_id} — {current.title}" if current is not None else "none"
    )
    lines = [
        CONTEXT_START,
        "## Active Goal (managed by Goals — do not edit between these markers)",
        "",
        f"**Objective:** {snapshot.objective}",
        f"**Current phase:** {phase_line}",
    ]
    if snapshot.definition_of_done:
        lines += ["", "**Definition of done:**", *_bullets(snapshot.definition_of_done)]
    if current is not None and current.acceptance_criteria:
        lines += [
            "",
            f"**Acceptance criteria for {current.phase_id}:**",
            *_bullets(current.acceptance_criteria),
        ]
    lines += [
        "",
        "**Working agreement:** Read `.goals/GOAL.md` for full phase, acceptance, "
        "and evidence state, and `.goals/goal-state.json` for the machine-readable "
        "spec. Work only on the current phase, record evidence, and run "
        "`goals check` before review.",
        CONTEXT_END,
    ]
    return "\n".join(lines)


def sync_context_files(
    cwd: Path, *, targets: tuple[str, ...] = CONTEXT_TARGETS
) -> ContextSyncResult:
    """Idempotently sync the managed goal block into context files.

    Human-authored content outside the markers is always preserved. Files are
    created if missing, the block is replaced in place if present, or appended
    if the file exists without markers.
    """
    snapshot = load_active_snapshot(cwd)
    worktree = Path(snapshot.topology.worktree_path)
    block = render_context_block(snapshot)
    result = ContextSyncResult()
    for name in targets:
        path = worktree / name
        if not path.exists():
            atomic_write_text(path, _new_context_file(name, block))
            result.created.append(name)
            continue
        existing = path.read_text(encoding="utf-8")
        updated = _replace_block(existing, block)
        if updated == existing:
            result.unchanged.append(name)
        else:
            atomic_write_text(path, updated)
            result.updated.append(name)
    return result


def _new_context_file(name: str, block: str) -> str:
    heading = name.removesuffix(".md").replace("_", " ").title()
    return f"# {heading}\n\n{block}\n"


def _replace_block(existing: str, block: str) -> str:
    if CONTEXT_START in existing and CONTEXT_END in existing:
        before, _, rest = existing.partition(CONTEXT_START)
        _, _, after = rest.partition(CONTEXT_END)
        return f"{before.rstrip()}\n\n{block}\n{after.lstrip(chr(10))}".rstrip() + "\n"
    return existing.rstrip() + "\n\n" + block + "\n"


# --------------------------------------------------------------------------- #
# 3. Native stop-condition emitter
# --------------------------------------------------------------------------- #
def build_native_goal_emission(
    snapshot: GoalSnapshot, adapter: NativeAdapter
) -> NativeGoalEmission:
    """Derive a transcript-verifiable native stop-condition from acceptance."""
    current = _current_phase_or_none(snapshot)
    criteria = current.acceptance_criteria if current is not None else []
    phase_id = current.phase_id if current is not None else "the current phase"
    criteria_text = "; ".join(criteria) if criteria else "the phase definition of done"
    condition = (
        f"Every acceptance criterion for Goals phase {phase_id} is satisfied "
        f"({criteria_text}), `goals check` reports `Overall: pass` with nothing "
        f"under `Needs The User`, and `goals phase accept {phase_id}` has run "
        "successfully."
    )
    if adapter == "claude":
        # Typed into Claude Code's prompt (a slash command), not a shell — the
        # backticks in `condition` are literal markdown here.
        command = f"/goal {condition}"
        notes = [
            "Paste the line into Claude Code with the `/goal` command; its Stop "
            "hook keeps the session working until the condition holds.",
            "The native check reads only the transcript — keep the durable proof "
            "in `.goals/goal-state.json` via `goals phase evidence`.",
        ]
    else:
        # Pasted into Codex as the task's definition of done — NOT a shell
        # command. Never wrap in `codex "..."`: the condition contains backticks
        # that a shell would execute as command substitution (e.g. running
        # `goals phase accept`) the moment it is pasted into a terminal.
        command = condition
        notes = [
            "Paste this as the task's definition of done in Codex; it is task "
            "text, not a shell command.",
            "If the local Codex goal feature is unavailable, paste it into the "
            "current session and let Goals remain the state layer.",
        ]
    return NativeGoalEmission(
        adapter=adapter, condition=condition, command=command, notes=notes
    )


def emit_native_goal(cwd: Path, adapter: NativeAdapter) -> NativeGoalEmission:
    return build_native_goal_emission(load_active_snapshot(cwd), adapter)


def render_native_goal_emission(emission: NativeGoalEmission) -> str:
    if emission.adapter == "claude":
        label = "Paste into Claude Code (a `/goal` prompt line, not a shell command):"
    else:
        label = "Paste into Codex as the task's definition of done (task text, not a shell command):"
    lines = [
        f"# Native goal condition ({emission.adapter})",
        "",
        label,
        "",
        f"    {emission.command}",
        "",
        "Notes:",
        *_bullets(emission.notes),
    ]
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #
def _current_phase_or_none(snapshot: GoalSnapshot) -> Phase | None:
    if snapshot.current_phase is None:
        return None
    for phase in snapshot.phases:
        if phase.phase_id == snapshot.current_phase:
            return phase
    return None


def _bullets(items: list[str]) -> list[str]:
    if not items:
        return ["- None recorded."]
    return [f"- {item}" for item in items]


def render_export(export: PortableExport) -> str:
    return "\n".join(
        [
            "# Portable Goal Export",
            "",
            f"Spec version: {export.spec_version}",
            f"Goal id: {export.goal_id}",
            f"Phases: {export.phase_count}",
            f"State: `{export.state_path}`",
            f"Markdown: `{export.markdown_path}`",
            "",
            "These files are sanitized of local paths and safe to commit so any "
            "agent can resume the goal.",
        ]
    ) + "\n"


def render_context_sync(result: ContextSyncResult) -> str:
    def line(label: str, names: list[str]) -> str:
        return f"- {label}: {', '.join(names) if names else 'none'}"

    return "\n".join(
        [
            "# Context Sync",
            "",
            line("Created", result.created),
            line("Updated", result.updated),
            line("Unchanged", result.unchanged),
            "",
            "Human-authored content outside the `goals:context` markers is "
            "preserved.",
        ]
    ) + "\n"
